### PR TITLE
add i18n and translate to zh-CN

### PR DESCRIPTION
**Pull request by ArthurDarkstone**
add i18n

translate to zh-CN by Gemini

### CODE REVIEW

**Comment by tjbck** [comment]
We should write somewhere that for the latest version of doc, only the english version will be monitored and kept up-to-date by the maintainers. The rest looks good to me!

**Comment by ArthurDarkstone** [comment]
> We should write somewhere that for the latest version of doc, only the english version will be monitored and kept up-to-date by the maintainers. The rest looks good to me!我们应该在某处写，对于最新版本的文档，只有英文版本会受到维护者的监控和更新。其余的对我来说看起来不错！

agreed. the English translated version now is several versions ahead of the translated. thats a problem.

**Comment by ArthurDarkstone** [comment]
for the english version, add the tip: 'only the english version will be monitored and kept up-to-date by the maintainers'

for the zh-CN version, add the same tip and mention the translator which is me.

**Comment by ArthurDarkstone** [comment]
@tjbck Is there any problem? It has been blocked for several weeks

**Comment by ArthurDarkstone** [comment]
Closing due to conflicts

**Pull request closed without merging**
