### PR TITLE
Troubleshoot steps for [SSL: CERTIFICATE_VERIFY_FAILED]

### PR DESCRIPTION
**Pull request by nomppy**
Docs for resolving SSL verification issues: https://github.com/open-webui/open-webui/issues/1398

### CODE REVIEW

**Comment by justinh-rahb** [comment]
I think this would be more appropriately added to the Tutorials, not the main doc page.

**Comment by nomppy** [comment]
You mean as Tutorial: set up with corporate SSL?

**Comment by nomppy** [comment]
moved!

**Comment by justinh-rahb** [comment]
LGTM

**Pull request merged**
