### PR TITLE
Update env-configuration.md

### PR DESCRIPTION
**Pull request by silentoplayz**
**Environment Variable Updates**

In this PR, I've made the following changes:

**Removed:**

* Environment variables that were documented but not accessed:
```
ENABLE_LITELLM
LITELLM_PROXY_HOST
LITELLM_PROXY_PORT
PORT
RAG_WEB_SEARCH_DOMAIN_FILTER_LIST
http_proxy
https_proxy
no_proxy
```
* Deprecated environment variables:
```
OLLAMA_API_BASE_URL
SEARCH_QUERY_PROMPT_LENGTH_THRESHOLD
```
* Removed the LiteLLM section to avoid confusion.

**Added:**

* New environment variables:
```
USER_PERMISSIONS_CHAT_EDITING
USER_PERMISSIONS_CHAT_TEMPORARY
ENABLE_ADMIN_CHAT_ACCESS
ENABLE_MESSAGE_RATING
DEFAULT_LOCALE
FUNCTIONS_DIR
FONTS_DIR
CORS_ALLOW_ORIGIN
CONTENT_EXTRACTION_ENGINE
TIKA_SERVER_URL
RAG_FILE_MAX_COUNT
RAG_FILE_MAX_SIZE
ENABLE_SEARCH_QUERY
SEARCHAPI_API_KEY
SEARCHAPI_ENGINE
AUDIO_TTS_API_KEY
AUDIO_TTS_SPLIT_ON
AUTOMATIC1111_API_AUTH
COMFYUI_WORKFLOW
TOOLS_DIR
```
**Other Improvements:**

* Updated prompt templates
* Rearranged environment variables in the documentation for better organization
* Added missing environment variables that were previously undocumented

Special thanks to @cheahjs for contributing new environment variables and creating a script to scan for missing env vars in the documentation ([PR #207](https://github.com/open-webui/docs/pull/207)).

### CODE REVIEW

**Comment by silentoplayz** [comment]
Didn't realize I did duplicate work. Apologies @cheahjs, should I close this?

**Comment by silentoplayz** [comment]
Understood! Will fix these hiccups now. 👍🏼

**Comment by tjbck** [comment]
Ready to be merged?

**Comment by silentoplayz** [comment]
Yes

**Comment by tjbck** [comment]
Thanks!

**Pull request merged**
