### PR TITLE
Create openedai-speech-integration.md

### PR DESCRIPTION
**Pull request by silentoplayz**
**Description:**

This PR adds a new documentation page, `openedai-speech-integration.md`, which provides a step-by-step guide on integrating `openedai-speech` into Open WebUI using Docker Desktop.

The guide covers the following topics:

* Creating a new folder for the `openedai-speech` service
* Creating a `docker-compose.yml` file
* Creating an optional `.env` file
* Running `docker-compose` to start the `openedai-speech` service
* Configuring Open WebUI to use `openedai-speech`
* Choosing a voice
* Troubleshooting common issues

This documentation aims to provide a clear and concise guide for users to integrate `openedai-speech` into Open WebUI, enabling them to generate naturally sounding voices.

**Changes:**

* Added `openedai-speech-integration.md` to the documentation directory.

**Checklist:**

* [x] The documentation is clear and concise.
* [x] The guide is easy to follow and understand.
* [x] The troubleshooting section covers common issues.

### CODE REVIEW

**Comment by silentoplayz** [comment]
This is a rough draft.

**Comment by tjbck** [comment]
Honestly LGTM as-is.

**Comment by silentoplayz** [comment]
> Honestly LGTM as-is.

If it looks good to you as is, we could put it on the docs now, as it should be sufficient enough to get people up and running with openedai-speech in a Docker container and integrating its functionality into Open WebUI for TTS.

**Comment by tjbck** [comment]
Thanks!

**Pull request merged**
