### PR TITLE
feat: add contributing tutorial and gh-pages workflow

### PR DESCRIPTION
**Pull request by matthewhand**
### **Pull Request Title:**  
Add Contributing Guidelines and Update GitHub Pages Workflow with Environment Variables  

---

### **Description:**  
This pull request introduces two contributions:  

1. **Contributing Guidelines:**  
   - Adds a new file at `docs/tutorials/tips/contributing-tutorial.md`.  
   - This document provides guidance for contributing code, reporting issues, improving documentation, and engaging with the community.

2. **GitHub Pages Workflow Update:**  
   - Modifies the `.github/workflows/gh-pages.yml` to support **forked repositories** by introducing two new environment variables:
     - **`SITE_URL`**: Defines the custom site URL used for GitHub Pages deployment.
     - **`BASE_URL`**: Configures the base path for deployments.
   - These variables ensure forked repositories can use custom URLs for deployments without conflicts.

---

### **Files Added/Modified:**  
- **`docs/tutorials/tips/contributing-tutorial.md`**  
  - Provides:
    - Community tutorial contribution practices and best practices.

- **`.github/workflows/gh-pages.yml`**  
  - Adds `SITE_URL` and `BASE_URL` environment variables to the deployment workflow to enable customized URLs for forked repositories.

---

### **Steps to Validate:**  
1. **Review the Contributing Tutorial:**  
   - Confirm the content in `docs/tutorials/tips/contributing-tutorial.md` is comprehensive and clear.
   - Ensure it aligns with the project's contribution policies and practices.

2. **Test the GitHub Pages Workflow:**  
   - Add the **`SITE_URL`** and **`BASE_URL`** secrets to your forked repository.
   - Push changes to the `main` branch and confirm the deployment reflects the custom URLs.

---

### **Checklist:**  
- [x] Verified the content of the contributing tutorial.  
- [x] Confirmed the GitHub Pages workflow functions with the environment variables.  
- [x] All changes align with the repository’s standards.
```

### CODE REVIEW

**Comment by tjbck** [comment]
Conflicts?

**Comment by matthewhand** [comment]
should be fixed with #261. maybe you can rerun the CI?

**Comment by matthewhand** [comment]
seems this file is special, potentially autogenerated when github pages is enabled. and for that reason it seems difficult (impossible?) to cleanly include the differences in this PR.  

so I have removed `.github/workflows/gh-pages.yml` from the PR, leaving just `docs/tutorials/tips/contributing-tutorial.md`.  I would have preferred an atomic commit. but given the special situation, it seems easiest if you just make the update on your end.

**Comment by tjbck** [comment]
Cherry-picked changes, Thanks!

**Pull request closed without merging**
